### ISSUE TITLE
Possible CFLint Changes

### ISSUE THREAD

**Issue by jjames967** [ditinc/linter-cflint#10]
Great job on setting up the plugin. I didn't know one for Atom existed. I just installed it as a package and was very helpful.

I may be pulling the CFLint-all.jar out in the next release, because we're switching to a gradle build. It should no longer be necessary, as you wouldn't need to install Maven locally. However, how much of a headache would this cause? I'd be more than happy to help you incorporate Gradle into your current project.

**Comment by sjmatta** [comment]
Thanks! :grinning: 

As far as CLint-all.jar goes - I'm building it from source for now and bundling it, but I'd actually prefer to grab your release version at install time (from someplace like Sonatype Nexus or Maven Central?). Whether it's built with Maven or Gradle probably won't affect this plugin at all since it only needs the final JAR artifact.

**Comment by sjmatta** [comment]
The reason I'm building it from source instead of grabbing the one from mvnrepository.org is because for on-the-fly linting, I had to add `stdin` and `stdout` capability. See my pull request at: https://github.com/cflint/CFLint/pull/83 (I'd be happy to make any changes you need me to, to the pull request).

**Comment by jjames967** [comment]
awesome. Looks like Ryan sent his recommendations on adding that. I'll give some time for the dev branch to get updated and tested before I send out a release, but glad to know it could help you as well.

**Comment by ryaneberly** [comment]
You can probably close this one.
